name: Python Application

on:
  push:
    branches: [ "main" ]

jobs:
  dev-job:
    name: Run Dev Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run dev.py
        run: python dev.py

  test-job:
    name: Run Test Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run test.py
        run: python test.py

  prod-job:
    name: Run Prod Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run prod.py
        run: python prod.py
