name: Python Application

on:
  push:
    branches: [ "main" ]

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run dev code
        run: python dev.py

      - name: Run test code
        run: python test.py

      - name: Run prod code
        run: python prod.py
